version: '3.7'

services:
  pizza-nginx:
    image: nginx:latest
    container_name: pizza-nginx
    depends_on:
      - pizza-php
    ports:
      - "80:80"
    volumes:
      - ./docker-conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-conf/nginx/conf.d/pizza.local.conf:/etc/nginx/conf.d/pizza.local.conf
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
    networks:
      - pizza-network
    tty: true

  pizza-php:
    build: 
      context: .
      dockerfile: docker-conf/php-fpm/Dockerfile
    container_name: pizza-php
    depends_on:
      - pizza-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./:/var/www/html/
    networks:
      - pizza-network
    tty: true

  pizza-mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: pizza-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./docker-conf/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker-conf/mysql/data:/var/lib/mysql
    networks:
      - pizza-network
    tty: true

networks:
  pizza-network: