version: '3.7'

services:
  pizza-nginx:
    image: nginx:latest
    container_name: pizza-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker-conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-conf/nginx/conf.d/pizza.local.conf:/etc/nginx/conf.d/pizza.local.conf
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
    depends_on:
      - pizza-php

  pizza-php:
    image: php:8.1-fpm
    container_name: pizza-php
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./vendor:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
